<?php View::content() ?>

<?php echo Tag::css("slick") ?>
<?php echo Tag::css("slick-theme") ?>
<?php echo Tag::js("slick") ?>
<?php echo Tag::js("funciones") ?>
<!-- http://kenwheeler.github.io/slick/ -->
<div class="techo"></div>
<div class="form-principal">
	<form action="">
		<div class="form-group">
			<input type="text" class="form-control-remate2" placeholder="Nombre">
		</div>
		<div class="form-group">
			<input type="text" class="form-control-remate2" placeholder="Email">
		</div>
		<div class="form-group">
			<input type="text" class="form-control-remate2" placeholder="Asunto">
		</div>
		<div class="form-group">
			<textarea name="" id="" placeholder="Mensaje" class="form-control-remate-textarea" cols="30" rows="10"></textarea>
		</div>
		<input type="submit" class="boton-remate" value="Enviar">
	</form>
</div>
<div class="your-class">
    <div><center><?php echo Html::img("descarga1.jpg","","width='90%'") ?></center></div>
    <div><center><?php echo Html::img("descarga2.jpg","","width='90%'") ?></center></div>
    <div><center><?php echo Html::img("descarga3.jpg","","width='90%'") ?></center></div>
</div>
