<?php View::content() ?>

<?php echo Tag::css("slick") ?>
<?php echo Tag::css("slick-theme") ?>
<?php echo Tag::js("slick") ?>
<?php echo Tag::js("funciones") ?>
<!-- http://kenwheeler.github.io/slick/ -->
<div class="techo"></div>
<div class="your-class">
    <div><center><?php echo Html::img("descarga1.jpg","","width='90%'") ?></center></div>
    <div><center><?php echo Html::img("descarga2.jpg","","width='90%'") ?></center></div>
    <div><center><?php echo Html::img("descarga3.jpg","","width='90%'") ?></center></div>
</div>
